# SPDX-License-Identifier: Apache-2.0
"""Generate the buy list, the print list and the build order FROM THE MODEL.

METHOD rule 1: generated files are outputs, not sources. Do not hand-edit
docs/BUY.md, docs/PRINT.md or docs/BUILD.md -- every number in them comes from
model/boat.py, and editing the output just means the two disagree. Change the
model and re-run:

    .venv/bin/python tools/emit_docs.py
"""
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "model"))
sys.path.insert(0, os.path.join(HERE, "tools"))
import boat  # noqa: E402

B = boat.build(boat.Config())
C = B["config"]
DOCS = os.path.join(HERE, "docs")
BANNER = ("<!-- GENERATED by tools/emit_docs.py from model/boat.py. Do not edit: "
          "change the model and re-run. -->\n\n")


def mm(v):
    return f"{v:.1f}"


def buy():
    lines = B["bom"]["lines"]
    out = [BANNER, "# Buy list\n\n",
           f"**{len(lines)} lines, {B['build_cost_usd']:.2f} USD total, "
           f"budget {C['budget_usd']:.0f} USD.**\n\n",
           "Prices are USD and Amazon US unless the line says otherwise. Amazon refused "
           "every product-page fetch during sourcing, so **only the lines marked "
           "`price VERIFIED` have a price checked on a page that could be loaded** -- "
           "the rest are estimates and the total is +/-25%, not a quote. Every ASIN "
           "came from a live `amazon.com/dp/` URL; none is invented. The search string "
           "is given for every line because a stale ASIN is worse than useless and a "
           "search is not.\n\n"]
    out.append("| Part | What | Qty | USD | Find it | Confidence |\n")
    out.append("|---|---|---|---|---|---|\n")
    for ln in lines:
        pn = ln["mpn"]
        find = (f"ASIN `{pn}`" if pn.startswith("B0") and len(pn) == 10
                else f"search: *{pn}*")
        out.append(f"| `{ln['ref']}` | {ln['description']} | {ln['qty_per_unit']} | "
                   f"{ln['unit_price']:.2f} | {find} | {ln['attributes']['confidence']} |\n")
    out.append(f"\n**Total {B['build_cost_usd']:.2f} USD.**\n")

    out.append("\n## Why these, and what lost\n\n")
    for ln in lines:
        if ln.get("note"):
            out.append(f"### `{ln['ref']}` — {ln['description']}\n\n{ln['note']}\n\n")
            if ln.get("manufacturers") and len(ln["manufacturers"]) > 1:
                out.append(f"*Alternatives:* {'; '.join(ln['manufacturers'][1:])}\n\n")
    out.append("\n## What is in the boat, and where\n\n")
    out.append("| Part | Mass g | Position x mm from transom |\n|---|---|---|\n")
    at = boat.G._sampler(boat.Config())
    comps = boat.place_components(boat.Config(), at)
    for k, d in sorted(comps.items(), key=lambda kv: kv[1]["centre"][0]):
        out.append(f"| {k} | {d['part'].mass_g:.0f} | {d['centre'][0]:.0f} |\n")
    out.append(f"\nPrinted structure {B['printed_mass_g']:.0f} g + components "
               f"{B['component_mass_g']:.0f} g + {C['mass_contingency_frac']*100:.0f}% "
               f"contingency = **{B['all_up_mass_g']:.0f} g all-up**, which floats at "
               f"**{B['draft_mm']:.1f} mm draft** with "
               f"**{B['trimmed_freeboard_mm']:.1f} mm of freeboard** once the trim is "
               f"taken into account.\n")
    return "".join(out)


def prints():
    pg = B["part_geometry"]
    order = sorted(pg.items(), key=lambda kv: -kv[1]["mass_g"])
    out = [BANNER, "# Print list\n\n",
           f"**{len(pg)} parts, {B['printed_mass_g']:.0f} g of filament, "
           f"{B['total_print_time_h']:.1f} h estimated.**\n\n",
           f"Material {C['material'].upper()}, {C['nozzle_mm']} mm nozzle, "
           f"{C['layer_mm']} mm layers, {C['perimeters']} perimeters, "
           f"{C['infill_frac']*100:.0f}% infill, {C['print_speed_mm_s']:.0f} mm/s, on a "
           f"{C['bed_x_mm']:.0f} x {C['bed_y_mm']:.0f} x {C['bed_z_mm']:.0f} mm bed.\n\n",
           "STLs are in `build/`. **Print the files in `build/print/`, not the ones in "
           "`build/`** -- they are the same solids, but `build/print/` has each part "
           "already laid on the bed in the orientation every printability verdict was "
           "made against. The files in `build/` are in assembly coordinates and are "
           "there for the viewer and the clash check.\n\n",
           "PETG needs four perimeters to be watertight untreated, which is why the "
           "shell is 1.6 mm. The interior epoxy coat is belt and braces on the one "
           "thing that cannot be fixed after assembly.\n\n"]
    out.append("| Part | Print bbox mm | Mass g | Time h | Orientation | Support |\n")
    out.append("|---|---|---|---|---|---|\n")
    times = B["print_time_by_part_h"]
    for k, g in order:
        bb = g["print_bbox_mm"]
        axis, flip = g["print_orientation"]
        ori = {"x": "standing on a transverse face", "y": "web flat",
               "z": "flat on the bed"}[axis] + (", flipped" if flip else "")
        sup = ("yes, ~%.0f mm2 at the stem" % (g["overhang_fraction"] * g["surface_area_mm2"])
               if g["overhang_fraction"] > 0.005 else "none")
        out.append(f"| `{k}` | {bb[0]:.0f} x {bb[1]:.0f} x {bb[2]:.0f} | {g['mass_g']:.0f} | "
                   f"{times[k]:.1f} | {ori} | {sup} |\n")
    out.append(f"\nLargest footprint {max(max(g['print_bbox_mm'][:2]) for g in pg.values()):.0f} mm "
               f"against {C['bed_x_mm'] - 2*C['brim_mm']:.0f} mm of usable bed once the brim is on.\n")
    out.append("\n## Plates\n\n")
    import render  # noqa: E402
    ps = render.load(os.path.join(HERE, "build", "print"))
    _, n_plates = render.plate(ps)
    out.append(f"These {len(ps)} parts bin into **{n_plates} bed{'s' if n_plates != 1 else ''}** "
               f"of 220 mm (tools/render.py, shelf-packed, 8 mm between parts). Three of "
               f"them are the full 186 mm beam of the boat on one axis, and two of those "
               f"cannot share a 220 mm bed with anything, which is what sets the floor.\n\n")
    out.append("\n## Fasteners — where every screw goes\n\n"
               "**M3 throughout, into brass heat-set inserts, never threaded into the "
               "plastic.** A thread cut in printed PETG strips after a few cycles and "
               "the hatch is opened every session. Stainless or nylon screws, not "
               "zinc-plated: zinc beside brass in fresh water is a rust streak within "
               "a season.\n\n")
    out.append("| Interface | Screws | Into | Blind? |\n|---|---|---|---|\n")
    out.append("| hatch cover | 4 x M3 x 12 | inserts in the coaming, which widens to "
               "8.6 mm at each screw | yes |\n")
    out.append("| motor clamp | 4 x M3 x 10 | inserts in the two cradle ribs | yes |\n")
    out.append("| servo | 2 x M3 x 10 | inserts in the servo shelf rib | yes |\n")
    out.append("| rudder bracket | 2 x M3 x 8 | inserts in a thickened pad on the "
               "INSIDE of the transom | **no — through the transom** |\n")
    out.append("| battery | none — hook-and-loop strap between two printed chocks | | |\n")
    out.append("| ESC, receiver | none — double-sided tape or hook-and-loop | | |\n")
    out.append("\n10 inserts, 12 screws. Set the inserts with a soldering iron at "
               "about 220 C, square to the boss, and let them cool before loading. "
               "**Every boss is blind except the rudder bracket's two**, which is the "
               "whole point of the next section.\n\n")

    out.append("\n## Hull penetrations — every hole through a pressure boundary\n\n")
    out.append(f"The boat floats at **{B['draft_mm']:.1f} mm** of draft. A hole below "
               f"that line is a leak path, so the layout puts everything it can above "
               f"it. `boat.hull_penetrations` is the gate that keeps it that way -- it "
               f"compares against the waterline the hydrostatics produce on the run, "
               f"not a number typed beside it.\n\n")
    out.append("| Penetration | Through | Height above keel | vs waterline | Sealed by |\n")
    out.append("|---|---|---|---|---|\n")
    for pn in B["penetrations"]:
        rel = float(pn["z_mm"]) - B["draft_mm"]
        tag = f"**{rel:+.0f} mm — BELOW**" if rel < 0 else f"{rel:+.0f} mm"
        out.append(f"| `{pn['name']}` | {pn['through']} | {float(pn['z_mm']):.0f} mm | "
                   f"{tag} | {pn['seal']} |\n")
    out.append("\nNo wire pierces a watertight bulkhead: the motor, ESC, battery, "
               "receiver and servo are all between the two bulkheads, so all four runs "
               "stay inside the equipment bay. That is a layout decision, not luck.\n\n")

    out.append("\n## Holes to drill after printing\n\n"
               "Nothing below is printed as a hole: a printed hole in a thin wall is a "
               "support problem and a drill is four seconds.\n\n")
    out.append(f"- **Stuffing tube**, through the hull bottom at x = "
               f"{B['shaft_exit_x_mm']:.0f} mm, at {B['shaft_angle_deg']:.0f} degrees "
               f"down-aft, and through `shaft_block` on the same line. **10.2 mm** for a "
               f"9.5 mm tube plus an epoxy fillet.\n")
    out.append("- **Pushrod tube**, through `bulkhead_aft` and `transom_plate` at the "
               "same height, above the waterline. 3.2 mm.\n")
    out.append("- **Limber holes**, 6 mm, through the foot of the centre girder inside "
               "`hull_mid`, every 40 mm, so bilge water can reach one place instead of "
               "two.\n")
    out.append("- **Hatch screws**, 4 x 2.5 mm pilot through the lid into the coaming "
               "for M3 self-tappers.\n")
    out.append("- **Insert bores**, 4.2 mm, 6 mm deep: 4 in the hatch coaming (at its "
               "widened zones), 4 in the motor cradle ribs, 2 in the servo shelf rib, "
               "2 in the transom pad. Ten in total.\n")
    out.append("- **Clearance holes**, 3.4 mm: 4 through the hatch cover, 4 through the "
               "motor clamp's feet, 2 through the rudder bracket, 2 through the "
               "transom for the rudder bracket.\n")
    out.append("- **Joint pins**, 2 mm through each of the two hull-to-hull joint faces, "
               "for 1.75 mm filament shear pins. Three per joint. There are only two "
               "joints left: the bulkheads that used to be loose plates are now printed "
               "into the segments.\n")
    out.append("- **Rudder bracket**, to the transom, to suit the bracket you get: its "
               "hole spacing is not published by the vendor. Measure first.\n")
    return "".join(out)


def build_order():
    out = [BANNER, "# Build order\n\n",
           "Written in the order that lets you find a mistake while it is still cheap.\n\n",
           "Six printed parts, two glued hull joints. The transom, both watertight "
           "bulkheads, the centre girder, the shaft seat and the aft deck are printed "
           "into the hull segments rather than glued on -- a bulkhead with no bond line "
           "cannot leak at the bond line.\n\n"]
    out.append("## 1. Print and leak-test the three hull segments BEFORE anything else\n\n"
               "Print `hull_aft`, `hull_mid` and `hull_bow`. Then, and this is the step "
               "every source agrees on and everybody skips: **fill each segment with "
               "water, stand it on a dry towel, and leave it two or three hours.** Mark "
               "every damp spot. Coat only what leaked, from the inside, and re-test.\n\n"
               "Doing this now costs an evening. Doing it after the electronics are in "
               "costs the electronics.\n\n")
    out.append("## 2. Seal the inside\n\n"
               "One or two thin brush coats of XTC-3D on the INSIDE of every segment, "
               "seams first. Thin coats: pooled epoxy adds mass without adding sealing, "
               "and mass is the budget this hull spends its freeboard out of.\n\n"
               "`hull_aft` is open at its forward end and `hull_bow` at its bow end, "
               "which is how you get a brush into both sealed compartments. That access "
               "is the reason `stem_plate` and `deck_bow` are still separate parts.\n\n")
    out.append("## 3. Driveline, while hull_aft is still open\n\n")
    out.append(f"Drill the 10.2 mm stuffing-tube hole through the hull bottom at "
               f"x = {B['shaft_exit_x_mm']:.0f} mm at {B['shaft_angle_deg']:.0f} degrees, "
               "and ream the matching bore through the shaft seat that is printed into "
               "the hull floor on that line. Pass the tube through both and "
               "**epoxy-fillet it on BOTH sides, inside and out**. Pack it one third to "
               "one half full of marine grease from the propeller end. This is the only "
               "penetration below the waterline and it is where boats actually sink.\n\n")
    out.append("## 4. Foam the ends, then close them\n\n"
               "Fill the stern compartment (inside `hull_aft`) and the bow compartment "
               "(inside `hull_bow`) with closed-cell foam, around the stuffing tube and "
               "the pushrod tube. **Closed cell, not open**: open-cell foam is a sponge "
               "and becomes ballast. Then bond `stem_plate` into the bow and `deck_bow` "
               "onto hull_bow's sheer. Those compartments never open again, and they are "
               "what makes a swamped boat recoverable rather than gone.\n\n")
    out.append("## 5. Heat-set the inserts, before anything is glued\n\n"
               "Ten M3 brass inserts: 4 in the hatch coaming at its widened zones, 4 in "
               "the motor cradle ribs, 2 in the servo shelf rib, 2 in the pad on the "
               "inside of the transom. Drill 4.2 mm, 6 mm deep, then push each insert "
               "in with a soldering iron at about 220 C, square, and let it cool before "
               "you load it.\n\n"
               "Do it now, while every one of these is reachable with a straight arm. "
               "After the segments are joined, two of them are not.\n\n")
    out.append("## 6. Join the three segments\n\n"
               "Two joints, both landing on a printed bulkhead face. Drill 2 mm pin holes "
               "through each joint face, three per joint, and dry-fit with 1.75 mm "
               "filament pins before any glue. Then CA the joints to tack them and "
               "epoxy-fillet each seam on the inside, through the hatch.\n\n")
    out.append("## 7. Fit out the equipment bay\n\n")
    at = boat.G._sampler(boat.Config())
    comps = boat.place_components(boat.Config(), at)
    for k, d in sorted(comps.items(), key=lambda kv: kv[1]["centre"][0]):
        x, y, z = d["centre"]
        out.append(f"- **{k}** at x {x:.0f} mm, y {y:+.0f} mm, z {z:.0f} mm above the keel\n")
    out.append(f"\nThe battery is STRAPPED, not glued. It is {C['place']['battery'][0]:.0f} mm "
               f"from the transom in the model and sliding it is how you trim the boat: "
               f"the model floats {B['trim_deg']:+.2f} degrees and every 10 mm of battery "
               f"movement is worth roughly 0.1 degrees.\n\n")
    out.append("## 8. Rudder and steering\n\n"
               "Bolt the rudder bracket to the transom with 2 x M3 stainless, through "
               "the two 3.4 mm holes, into the inserts in the transom pad. **Bed each "
               "screw in neutral-cure RTV under a nylon washer** -- these are the only "
               "two fasteners on the boat that go through the shell, and although they "
               "are 9 mm above the waterline they are 9 mm above the waterline in "
               "flat calm. Measure the bracket you are actually sent first: its hole "
               "spacing is not published.\n\n"
               "Then feed the pushrod through its tube, clevis at each end, and set the "
               "servo to centre before you connect it.\n\n")
    out.append("## 9. Hatch\n\n"
               "Lay the foam tape on the coaming's top face -- the coaming is printed "
               "into `hull_mid`'s deck rails and continues across both bulkhead tops -- "
               "and screw `hatch_cover` down onto it with four M3 self-tappers. "
               "Silicone-grease the tape every session. **Never glue the hatch shut**: it "
               "is the only way back into the boat.\n\n")
    out.append("## 10. Before the first sail\n\n"
               "- Set the ESC to **Forward/Reverse**, not Forward/Brake/Reverse.\n"
               "- Set **throttle failsafe to neutral**. A lost link with the throttle open "
               "is how boats end up in the reeds.\n"
               "- Range-test on land with the hull closed, receiver where it will live.\n"
               "- Refill the hull with water one more time and leave it an hour.\n"
               "- Float it with the battery in and **check it sits level**. If it is down "
               "by the stern, slide the battery forward.\n"
               "- First run: five minutes, close to shore. Open it, look for water, feel "
               "the motor and the ESC.\n\n")
    out.append("## What this boat will and will not do\n\n")
    out.append(f"Design speed **{B['design_speed_m_s']:.1f} m/s**, which is Froude "
               f"{B['froude']:.2f} on a {B['loa_mm']:.0f} mm hull -- at hull speed. It is a "
               "displacement hull: past about 0.9 m/s it will squat by the stern, drag a "
               "large wake, and drink current without going meaningfully faster. That is "
               "not a fault, it is what the hull is.\n")
    return "".join(out)


if __name__ == "__main__":
    os.makedirs(DOCS, exist_ok=True)
    for name, text in (("BUY.md", buy()), ("PRINT.md", prints()), ("BUILD.md", build_order())):
        with open(os.path.join(DOCS, name), "w") as fh:
            fh.write(text)
        print("wrote docs/" + name)
